feat: added the 1.4 version of the syscall shell script.
Changes:
- Renamed syscall_hook_patches_older.sh to
syscall_hook_patches_early.sh.
- Renamed backport_patches_older.sh to backport_patches_early.sh.
- Added syscall_hook_patches_older.sh.
- Corrected the syscall explanation in the documentation.
- Fixed the syscall execution steps in all YAML files.

Co-authored-by: JackAltman
<82563979+JackA1ltman@users.noreply.github.com>

diff --git a/.github/workflows/build_kernel_older_redmi8_4.19_aosp_a15.yml b/.github/workflows/build_kernel_older_redmi8_4.19_aosp_a15.yml
--- a/.github/workflows/build_kernel_older_redmi8_4.19_aosp_a15.yml
+++ b/.github/workflows/build_kernel_older_redmi8_4.19_aosp_a15.yml
@@ -9,7 +9,7 @@ env:
   PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches" # [your_name]/[your_patch] -> gooder123/NonGKI_Patcher
   PATCHES_BRANCH: "mi_kernel" # [your_branch] -> main
   HOOK_METHOD: "syscall" # manual hook method,can choice syscall and normal.
-  HOOK_OLDER: "false" # contain backport older patch and syscall older patch.
+  HOOK_OLDER: "true" # contain backport older patch and syscall older patch.
   PROFILE_NAME: "olive_older_4.19_aosp_a15.env" # your profile name.
   KERNELSU_SUS_PATCH: "false" # if u need manual susfs patch to kernelsu.
   KPM_ENABLE: "true" # Only use it for SukiSU-Ultra.
@@ -423,9 +423,9 @@ jobs:
                   bash normal_patches.sh
                   echo "execuated patch successfully."
                   if [[ "${{ env.KERNELSU_NAME }}" != "KernelSU-Next" ]]; then
-                        cp /tmp/Patches/backport_patches_older.sh ./
+                        cp /tmp/Patches/backport_patches_early.sh ./
                         bash backport_patches_older.sh
-                        echo "execuated backport patch older successfully. "
+                        echo "execuated backport patch early successfully. "
                   else
                       echo "your kernel needn't backport patch."
                   fi
@@ -438,19 +438,24 @@ jobs:
                    cp /tmp/Patches/syscall_hook_patches_older.sh device_kernel/
                    cd device_kernel
                    bash syscall_hook_patches_older.sh
-                   echo "execuated syscall patch successfully."
+                   echo "execuated syscall patch older successfully."
                    if [[ "${{ env.KERNELSU_NAME }}" != "KernelSU-Next" ]]; then
-                     cp /tmp/Patches/backport_patches_older.sh ./
-                     bash backport_patches_older.sh
-                     echo "execuated backport patch older successfully. "
+                     cp /tmp/Patches/backport_patches.sh ./
+                     bash backport_patches.sh
+                     if [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 10 ]; then
+                         cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_to_ksu.patch ./
+                         patch -p1 < backport_kernel_read_and_kernel_write_to_ksu.patch || true
+                         echo "execuated backport patch kernel_read and kernel_read successfully. If you current kernel version < 4.14, then u maybe manual fixed it."
+                     fi
+                     echo "execuated backport patch successfully. "
                    else
                      echo "your kernel needn't backport patch."
                    fi
-               elif [[ -f "/tmp/Patches/syscall_hook_patches_v1_4.sh" ]]; then
-                   cp /tmp/Patches/syscall_hook_patches_v1_4.sh device_kernel/
+               elif [[ -f "/tmp/Patches/syscall_hook_patches.sh" ]]; then
+                   cp /tmp/Patches/syscall_hook_patches.sh device_kernel/
                    cd device_kernel
-                   bash syscall_hook_patches_v1_4.sh
-                   echo "execuated syscall patch v1.4 successfully."
+                   bash syscall_hook_patches.sh
+                   echo "execuated syscall patch successfully."
                    if [[ "${{ env.KERNELSU_NAME }}" != "KernelSU-Next" ]]; then
                      cp /tmp/Patches/backport_patches.sh ./
                      bash backport_patches.sh
@@ -462,11 +467,12 @@ jobs:
                      echo "execuated backport patch successfully."
                    fi
                 else
-                   echo "Cannot found syscall_hook_patches_v1_4.sh in build project , please check u file existed in build project !"
+                   echo "Cannot found syscall_hook_patches.sh in build project , please check u file existed in build project !"
                    false
                fi
             else
               echo "please input vaild option!"
+              false
             fi
           fi
 
