mix2s: switched packaging and updated patching.
Changes:
- Ported full packaging functionality to the Xiaomi Mix 2S YAML.
- Updated the Xiaomi Mix 2S YAML's no-kprobe function to the latest
version.
- Switched the Xiaomi Mix 2S HOOK_METHOD to syscall.
- Changed the Xiaomi Mix 2S packaging method to Anykernel3.

Co-authored-by: JackAltman
<82563979+JackA1ltman@users.noreply.github.com>

diff --git a/.github/workflows/build_kernel_mix2s_evox_a15.yml b/.github/workflows/build_kernel_mix2s_evox_a15.yml
--- a/.github/workflows/build_kernel_mix2s_evox_a15.yml
+++ b/.github/workflows/build_kernel_mix2s_evox_a15.yml
@@ -3,7 +3,9 @@ on:
   workflow_call:
   workflow_dispatch:
 env:
-  HOOK_METHOD: "normal" # manual hook method,can choice syscall and normal.
+  PACK_METHOD: "Anykernel3" # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.
+  HOOK_METHOD: "syscall" # manual hook method,can choice syscall and normal.
+  HOOK_NEWER: "true"
   KPM_ENABLE: "true" # Only use it for SukiSU-Ultra.
   KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" # patch exec file source -> raw.githubusercontent.com/Test/Test/patch .
   GENERATE_CHIP: "qcom" # only supported for qcom and mediatek.
@@ -245,8 +247,6 @@ jobs:
       - name: Patch Kernel for no-kprobe
         run: |
           cd $GITHUB_WORKSPACE
-          KERNEL=$(echo "${{ env.KERNEL_VERSION }}" | awk -F '.' '{print $1}')
-          PATCHLEVEL=$(echo "${{ env.KERNEL_VERSION }}" | awk -F '.' '{print $2}')
           if grep -q "CONFIG_KSU" "device_kernel/fs/exec.c"; then
             echo "Your kernel source code appears to have been manually patched, so this step is skipped."
           else
@@ -257,9 +257,21 @@ jobs:
                   bash normal_patches.sh
                   echo "execuated patch successfully."
                   if [[ "${{ env.KERNELSU_NAME }}" != "KernelSU-Next" ]]; then
-                      cp /tmp/Patches/backport_patches.sh ./
-                      bash backport_patches.sh
-                      echo "execuated backport patch successfully."
+                      if [[ "${{ env.HOOK_NEWER }}" == "true" ]] && [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 10 ]; then
+                        cp /tmp/Patches/backport_patches_newer.sh ./
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_to_ksu.patch ./
+                        patch -p1 < backport_kernel_read_and_kernel_write_to_ksu.patch || true
+                        bash backport_patches_newer.sh
+                        echo "execuated backport patch newer successfully. If you current kernel version < 4.14, then u maybe manual fixed it."
+                      elif [[ "${{ env.HOOK_NEWER }}" == "true" ]]; then
+                        cp /tmp/Patches/backport_patches_newer.sh ./
+                        bash backport_patches_newer.sh
+                        echo "execuated backport patch newer successfully."
+                      else
+                        cp /tmp/Patches/backport_patches.sh ./
+                        bash backport_patches.sh
+                        echo "execuated backport patch successfully."
+                      fi
                   else
                       echo "your kernel needn't backport patch."
                   fi
@@ -274,9 +286,21 @@ jobs:
                   bash syscall_hook_patches.sh
                   echo "execuated syscall patch successfully."
                   if [[ "${{ env.KERNELSU_NAME }}" != "KernelSU-Next" ]]; then
-                      cp /tmp/Patches/backport_patches.sh ./
-                      bash backport_patches.sh
-                      echo "execuated backport patch successfully."
+                      if [[ "${{ env.HOOK_NEWER }}" == "true" ]] && [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 10 ]; then
+                        cp /tmp/Patches/backport_patches_newer.sh ./
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_to_ksu.patch ./
+                        patch -p1 < backport_kernel_read_and_kernel_write_to_ksu.patch || true
+                        bash backport_patches_newer.sh
+                        echo "execuated backport patch newer successfully. If you current kernel version < 4.14, then u maybe manual fixed it."
+                      elif [[ "${{ env.HOOK_NEWER }}" == "true" ]]; then
+                        cp /tmp/Patches/backport_patches_newer.sh ./
+                        bash backport_patches_newer.sh
+                        echo "execuated backport patch newer successfully."
+                      else
+                        cp /tmp/Patches/backport_patches.sh ./
+                        bash backport_patches.sh
+                        echo "execuated backport patch successfully."
+                      fi
                   else
                       echo "your kernel needn't backport patch."
                   fi
@@ -521,25 +545,143 @@ jobs:
               ;;
           esac
 
-      - name: Make Latest Boot Image
+      - name: Make Anykernel3 Flasher
+        if: env.PACK_METHOD == 'Anykernel3'
         run: |
-          IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot"
           TIME=$(date +"%Y%m%d%H%M%S")
 
-          cd $GITHUB_WORKSPACE
+          cd $GITHUB_WORKSPACE/device_kernel/
+          if [[ -d "arch/arm64/configs" ]]; then
+            IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot"
+          else
+            IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm/boot"
+          fi
 
+          mkdir -p tmp
+
+          if [[ "${{ env.AK3_SOURCE }}" =~ "osm0sis" ]]; then
+            sed -i 's/do.devicecheck=1/do.devicecheck=0/g' Anykernel3/anykernel.sh
+            sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' Anykernel3/anykernel.sh
+            sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' Anykernel3/anykernel.sh
+            echo "Now using official Anykernel3."
+          else
+            echo "Now using custom Anykernel3."
+          fi
+
+          if [[ -f "$IMAGE_DIR/Image.gz-dtb" ]]; then
+            cp -fp $IMAGE_DIR/Image.gz-dtb tmp
+            echo "Found Image.gz-dtb !"
+          elif [[ -f "$IMAGE_DIR/Image.gz" ]]; then
+            cp -fp $IMAGE_DIR/Image.gz tmp
+            echo "Found Image.gz !"
+          elif [[ -f "$IMAGE_DIR/zImage-dtb" ]]; then
+            cp -fp $IMAGE_DIR/zImage-dtb tmp
+            echo "Found zImage-dtb (ARMV7A) !"
+          elif [[ -f "$IMAGE_DIR/Image" ]]; then
+            # gzip -c $IMAGE_DIR/Image > $IMAGE_DIR/Image.gz
+            # cp -fp $IMAGE_DIR/Image.gz tmp
+            cp -fp $IMAGE_DIR/Image tmp
+            echo "Found Image !"
+          fi
+
+          if [[ -f "$IMAGE_DIR/dtbo.img" ]]; then
+            cp -fp $IMAGE_DIR/dtbo.img tmp
+            echo "Found dtbo.img !"
+          else
+            echo "Doesn't found dtbo.img! Your device maybe needn't the file."
+          fi
+
+          if [ -f "$IMAGE_DIR/dtb" ]; then
+            echo "Found DTB!"
+            cp -fp $IMAGE_DIR/dtb tmp
+          elif [ "${{ env.GENERATE_DTB }}" == "true" ]; then
+            if [ -d "$IMAGE_DIR/dts/vendor/${{ env.GENERATE_CHIP }}" ]; then
+                cat $IMAGE_DIR/dts/vendor/${{ env.GENERATE_CHIP }}/*.dtb > $IMAGE_DIR/DTB
+                cp -fp $IMAGE_DIR/DTB tmp
+                echo "Generated ${{ env.GENERATE_CHIP }} DTB."
+            elif [ -d "$IMAGE_DIR/dts/${{ env.GENERATE_CHIP }}" ]; then
+                cat $IMAGE_DIR/dts/${{ env.GENERATE_CHIP }}/*.dtb > $IMAGE_DIR/DTB
+                cp -fp $IMAGE_DIR/DTB tmp
+                echo "Generated ${{ env.GENERATE_CHIP }} DTB."
+            else
+                echo "Missing .dtb file in dts or dts/vendor ! Generate Failed !"
+                false
+            fi
+          else
+            echo "Doesn't found DTB! Your device maybe needn't the file."
+          fi
+
+          cp -rp ./Anykernel3/* tmp
+          cd tmp
+          7za a -mx9 tmp.zip *
+          cd ..
+          cp -fp tmp/tmp.zip ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}${{ env.LXC_STATUS }}.zip
+          rm -rf tmp
+
+          echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}${{ env.LXC_STATUS }}.zip" >> $GITHUB_ENV
+
+      - name: Make Latest Boot Image
+        if: env.PACK_METHOD == 'MKBOOTIMG'
+        run: |
+          cd $GITHUB_WORKSPACE/
+          IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot"
+          TIME=$(date +"%Y%m%d%H%M%S")
           FORMAT_MKBOOTING=$(echo `mkboottools/unpack_bootimg.py --boot_img=boot_source_${{ env.DEVICE_NAME }}.img --format mkbootimg`)
+
           mkboottools/unpack_bootimg.py --boot_img boot_source_${{ env.DEVICE_NAME }}.img
-          rm -f out/kernel
-          cp $IMAGE_DIR/Image.gz-dtb out/kernel
-          eval "mkboottools/mkbootimg.py $FORMAT_MKBOOTING -o ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image.img"
+
+          if [[ -f "$IMAGE_DIR/Image.gz-dtb" ]]; then
+            rm -f out/kernel
+            cp -fp $IMAGE_DIR/Image.gz-dtb out/kernel
+            echo "Found Image.gz-dtb !"
+          elif [[ -f "$IMAGE_DIR/Image.gz" ]]; then
+            rm -f out/kernel
+            cp -fp $IMAGE_DIR/Image.gz out/kernel
+            echo "Found Image.gz !"
+          elif [[ -f "$IMAGE_DIR/Image" ]]; then
+            rm -f out/kernel
+            cp -fp $IMAGE_DIR/Image out/kernel
+            echo "Found Image !"
+          fi
+
+          if [ -f "$IMAGE_DIR/dtb" ]; then
+            echo "Found DTB!"
+            cp -fp $IMAGE_DIR/dtb out/dtb
+          elif [ "${{ env.GENERATE_DTB }}" == "true" ]; then
+            if [ -d "$IMAGE_DIR/dts/vendor/${{ env.GENERATE_CHIP }}" ]; then
+                cat $IMAGE_DIR/dts/vendor/${{ env.GENERATE_CHIP }}/*.dtb > $IMAGE_DIR/DTB
+                cp -fp $IMAGE_DIR/DTB tmp
+                echo "Generated ${{ env.GENERATE_CHIP }} DTB."
+            elif [ -d "$IMAGE_DIR/dts/${{ env.GENERATE_CHIP }}" ]; then
+                cat $IMAGE_DIR/dts/${{ env.GENERATE_CHIP }}/*.dtb > $IMAGE_DIR/DTB
+                cp -fp $IMAGE_DIR/DTB tmp
+                echo "Generated ${{ env.GENERATE_CHIP }} DTB."
+            else
+                echo "Missing .dtb file in dts or dts/vendor ! Generate Failed !"
+                false
+            fi
+          else
+            echo "Doesn't found DTB! Your device maybe needn't the file."
+          fi
+
+          eval "mkboottools/mkbootimg.py $FORMAT_MKBOOTING -o ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image${{ env.LXC_STATUS }}.img"
+
+          echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image${{ env.LXC_STATUS }}.img" >> $GITHUB_ENV
 
           rm -f $GITHUB_WORKSPACE/boot_source_${{ env.DEVICE_NAME }}.img
-          echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-image.img" >> $GITHUB_ENV
 
-      - name: Upload Build Artifacts
+      - name: Upload Build Artifacts For Anykernel3
+        if: env.PACK_METHOD == 'Anykernel3'
         uses: actions/upload-artifact@v4
         with:
-          name: Kernel-${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-image
+          name: Kernel-${{ env.PACK_NAME }}
+          path: |
+            device_kernel/${{ env.PACK_NAME }}
+
+      - name: Upload Build Artifacts For Boot Image
+        if: env.PACK_METHOD == 'MKBOOTIMG'
+        uses: actions/upload-artifact@v4
+        with:
+          name: Kernel-${{ env.PACK_NAME }}
           path: |
             ${{ env.PACK_NAME }}
