Project version updated to v1.5.
- Renamed backport_set_memory.patch to set_memory_to_49_and_low.patch.
- Created the Patch directory.
- Moved set_memory_to_49_and_low.patch to the Patch directory.
- Moved susfs_upgrade_to_157.patch to the Patch directory.
- Added kernel version variable globalization to the example YAML file.
- Added backport set_memory section to the KPM Checker function in the
example YAML file.
- Added found_gcc.sh.
- Added automated GCC prefix detection to the example YAML file.
- Added documentation for found_gcc.sh.
- Added check_error.sh.
- Added documentation for check_error.sh.
- Added the "Analyze compile error" step to the example YAML file.
- Fixed missing and incorrect patches in set_memory_to_49_and_low.patch.
- Corrected patch-related adjustments in the documentation.
- Fixed the DTBO generation function in the example YAML file.
- Fixed kernel version retrieval and judgment in the example YAML file.
- Corrected the directory path for the SUSFS update patch in all YAML
files.
- Fixed modifications related to set_memory functionality for Xiaomi Mix
2S.
- Changed the release Tag to 1.5-r1.
- Deleted the temp_dtbo.patch entry from the documentation.
- Deleted temp_dtbo.patch.

diff --git a/.github/workflows/build_kernel_older_template.yml b/.github/workflows/build_kernel_older_template.yml
--- a/.github/workflows/build_kernel_older_template.yml
+++ b/.github/workflows/build_kernel_older_template.yml
@@ -127,6 +127,9 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE
 
+          # Copy Shell
+          cp /tmp/Patches/found_gcc.sh ./
+
           # Set GCC Aarch64
           if [[ "${{ env.CLANG_SOURCE }}" == *proton* ]]; then
             echo "Detected Proton Clang. Not use GCC Source."
@@ -153,8 +156,7 @@ jobs:
               mkdir gcc-64
               unzip gcc-64.zip -d gcc-64/
             fi
-            GCC_64_BIN=aarch64-linux-android-
-            echo "GCC_64=CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-64/bin/$GCC_64_BIN" >> $GITHUB_ENV
+            bash found_gcc.sh GCC_64
           fi
 
 
@@ -184,11 +186,10 @@ jobs:
               mkdir gcc-32
               unzip gcc-32.zip -d gcc-32/
             fi
-            GCC_32_BIN=arm-linux-androideabi-
             if [ -z "${{ env.GCC_64_SOURCE }}" ]; then
-                echo "GCC_32=CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-32/bin/$GCC_32_BIN" >> $GITHUB_ENV
+                bash found_gcc.sh GCC_32_ONLY
             else
-                echo "GCC_32=CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/gcc-32/bin/$GCC_32_BIN" >> $GITHUB_ENV
+                bash found_gcc.sh GCC_32
             fi
           fi
 
@@ -236,7 +237,14 @@ jobs:
                 $GITHUB_WORKSPACE/device_kernel/scripts/extract-ikconfig $GITHUB_WORKSPACE/device_kernel/Image > $GITHUB_WORKSPACE/device_kernel/arch/arm/configs/${{ env.DEFCONFIG_NAME }}
             fi
           fi
+
+
+          # Get KernelSU Version and Kernel Version
+
+          KERNEL_VERSION=$(head -n 3 $GITHUB_WORKSPACE/device_kernel/Makefile | grep -E 'VERSION|PATCHLEVEL' | awk '{print $3}' | paste -sd '.')
           echo "KERNEL_VERSION=$(head -n 3 device_kernel/Makefile | grep -E 'VERSION|PATCHLEVEL' | awk '{print $3}' | paste -sd '.')" >> $GITHUB_ENV
+          echo "FIRST_VERSION=$(echo "$KERNEL_VERSION" | awk -F '.' '{print $1}')" >> $GITHUB_ENV
+          echo "SECOND_VERSION=$(echo "$KERNEL_VERSION" | awk -F '.' '{print $2}')" >> $GITHUB_ENV
 
       - name: Set KSU and SUSFS for DEFCONFIG
         shell: bash
@@ -341,15 +349,22 @@ jobs:
           KSU_VERSION=$(cd ${{ env.KERNELSU_NAME }} && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
           echo "UPLOADNAME=-${{ env.KERNELSU_NAME }}_$KSU_VERSION" >> $GITHUB_ENV
 
-          ## KPM Checker
+          # KPM Checker
           if [[ -d "${{ env.KERNELSU_NAME }}/kernel/kpm" ]]; then
             if [ -f "include/linux/set_memory.h" ] && [ "${{ env.KPM_ENABLE }}" == "true" ]; then
                 echo "CONFIG_KPM=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
                 wget "${{ env.KPM_PATCH_SOURCE }}" -O patch
                 chmod a+x patch
                 echo "Set KPM successfully !"
-            elif [ "$KPM_ENABLE" == "true" ]; then
-                echo "Your kernel doesn't support KPM !"
+            elif [ "${{ env.KPM_ENABLE }}" == "true" ]; then
+                if [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 10 ]; then
+                    cp /tmp/Patches/Patch/set_memory_to_49_and_low.patch ./
+                    patch -p1 < set_memory_to_49_and_low.patch || true
+                    echo "Patch set_memory successfully !"
+                    echo "If have patch error (.rej), manual fixed it."
+                else
+                    echo "Your kernel cannot support KPM function."
+                fi
             else
                 echo "Doesn't enable KPM !"
             fi
@@ -435,17 +450,19 @@ jobs:
         if: env.HAVE_NO_DTBO == 'true' && env.HAVE_NO_DTBO_TOOL != 'true'
         shell: bash
         run: |
+          # Get MKDTBO tool to kernel
           cd $GITHUB_WORKSPACE/device_kernel/scripts/dtc
           wget https://android.googlesource.com/platform/system/libufdt/+archive/refs/heads/main/utils/src.tar.gz
           tar zxvf src.tar.gz
           rm -f src.tar.gz
 
+          # Hook dtbo generate code to kernel
           cd $GITHUB_WORKSPACE/device_kernel
-          cp /tmp/Patches/temp_dtbo.patch ./
-          patch -p1 < temp_dtbo.patch
           sed -i '/targets := Image Image.bz2 Image.gz Image.lz4 Image.lzma Image.lzo/s/$/ dtbo.img/' ./arch/arm64/boot/Makefile
+          sed -i '/# Add RTIC DTB to the DTB list if RTIC MPGen is enabled/i \DTBO_OBJS := $(shell find $(obj)/dts/ -name \\*.dtbo)\n' arch/arm64/boot/Makefile
           sed -i '/$(obj)\/Image\.gz-dtb: $(obj)\/Image\.gz $(DTB_OBJS) FORCE/a \#DTBO\n$(obj)\/dtbo.img: $(DTBO_OBJS) FORCE\n\t$(call if_changed,mkdtimg)' ./arch/arm64/boot/Makefile
           sed -i '/KBUILD_DTBS\t:= dtbs/a \#DTBO\nKBUILD_DTBO_IMG := dtbo.img' ./arch/arm64/Makefile
+          sed -i '/PHONY += vdso_install/i \ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)\n$(KBUILD_DTBO_IMG): dtbs\n\t$(Q)$(MAKE) $(build)=$(boot) $(boot)/$@\n\nall: $(KBUILD_DTBO_IMG)\nendif' arch/arm64/Makefile
           sed -i '/dtc-tmp = $(subst $(comma),_,$(dot-target)\.dts\.tmp)/a \#DTBO\n# mkdtimg\n#----------------------------------------------------------------------------\nquiet_cmd_mkdtimg = DTBOIMG $@\ncmd_mkdtimg = python3 $(srctree)\/scripts\/dtc\/mkdtboimg.py create $@ --page_size=4096 $(filter-out FORCE,$^)' ./scripts/Makefile.lib
 
       - name: Setup LXC (Experiment)
@@ -552,7 +569,7 @@ jobs:
         if: env.SUSFS_ENABLE == 'true' && env.SUSFS_UPDATE == 'true'
         run: |
           cd $GITHUB_WORKSPACE/device_kernel/
-          cp /tmp/Patches/susfs_upgrade_to_157.patch ./
+          cp /tmp/Patches/Patch/susfs_upgrade_to_157.patch ./
 
           patch -p1 < susfs_upgrade_to_157.patch || true
 
@@ -568,7 +585,6 @@ jobs:
           max-size: 2G
 
       - name: Build Kernel
-        shell: bash
         run: |
           MERGE_CONFIG_FILES=("vendor/debugfs.config" "vendor/lahaina_QGKI.config")
           export PATH=$GITHUB_WORKSPACE/clang-custom/bin:$PATH
@@ -581,7 +597,7 @@ jobs:
                 done
                 make CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} olddefconfig
             fi
-            make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }}
+            make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} 2>&1|tee error.log
           elif [ -z "${{ env.GCC_32 }}" ]; then
             make O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.DEFCONFIG_NAME }}
             if [[ "${{ env.BUILD_OTHER_CONFIG }}"  == "true" ]]; then
@@ -590,7 +606,7 @@ jobs:
                 done
                 make O=out ARCH=arm64 ${{ env.GCC_64 }} olddefconfig
             fi
-            make -j$(nproc --all) O=out ARCH=arm64 ${{ env.GCC_64 }}
+            make -j$(nproc --all) O=out ARCH=arm64 ${{ env.GCC_64 }} 2>&1|tee error.log
           elif [ -z "${{ env.GCC_64 }}" ]; then
             make O=out ARCH=arm ${{ env.GCC_64 }} ${{ env.DEFCONFIG_NAME }}
             if [[ "${{ env.BUILD_OTHER_CONFIG }}"  == "true" ]]; then
@@ -599,7 +615,7 @@ jobs:
                 done
                 make O=out ARCH=arm ${{ env.GCC_32 }} olddefconfig
             fi
-            make -j$(nproc --all) O=out ARCH=arm ${{ env.GCC_32 }}
+            make -j$(nproc --all) O=out ARCH=arm ${{ env.GCC_32 }} 2>&1|tee error.log
           elif [ -z "${{ env.CLANG_SOURCE }}" ]; then
             make O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.GCC_32 }} ${{ env.DEFCONFIG_NAME }}
             if [[ "${{ env.BUILD_OTHER_CONFIG }}"  == "true" ]]; then
@@ -608,7 +624,7 @@ jobs:
                 done
                 make O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.GCC_32 }} olddefconfig
             fi
-            make -j$(nproc --all) O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.GCC_32 }}
+            make -j$(nproc --all) O=out ARCH=arm64 ${{ env.GCC_64 }} ${{ env.GCC_32 }} 2>&1|tee error.log
           else
             make CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} ${{ env.DEFCONFIG_NAME }}
             if [[ "${{ env.BUILD_OTHER_CONFIG }}"  == "true" ]]; then
@@ -617,7 +633,7 @@ jobs:
                 done
                 make CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} olddefconfig
             fi
-            make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }}
+            make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 ${{ env.CUSTOM_CMDS }} ${{ env.EXTRA_CMDS }} ${{ env.GCC_64 }} ${{ env.GCC_32 }} 2>&1|tee error.log
           fi
 
           ## Generate DTBO
@@ -634,6 +650,14 @@ jobs:
                 python dtbo_tool/src/mkdtboimg.py create $GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dtbo.img $GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot/dts/${{ env.GENERATE_CHIP }}/*.dtbo
             fi
           fi
+
+      - name: Analyze compile error
+        if: env.BUILD_DEBUGGER == 'true' && always()
+        run: |
+          cd $GITHUB_WORKSPACE/device_kernel/
+
+          cp /tmp/Patches/check_error.sh ./
+          bash check_error.sh
 
       - name: KPM Patcher (Experiment)
         if: env.KPM_ENABLE == 'true'
